"""Generate mp3 pronunciations for every word in data/words.json.

Usage:
    pip install edge-tts
    python scripts/make_audio.py [--voice en-US-AriaNeural]

Writes audio/<slug>.mp3 (normal speed) and audio/slow/<slug>.mp3 (-30%).
Existing files are skipped, so re-running after new lessons only voices new words.
Also writes js/audio.js — the list of words that have an mp3, so the site doesn't request missing files.
The site falls back to the browser's speech synthesis for any word without an mp3.
"""
import argparse
import asyncio
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def speak_text(en):
    # keep in sync with speakText() in js/common.js
    s = re.sub(r"\([^)]*\)", "", en)
    s = re.sub(r"/+", ", ", s)
    return re.sub(r"\s+", " ", s).strip(" ,")


def slug(en):
    # keep in sync with slug() in js/common.js
    s = speak_text(en).lower().replace("’", "'")
    return re.sub(r"[^a-z0-9]+", "-", s).strip("-")


async def voice_one(edge_tts, text, path, voice, rate, proxy):
    for attempt in range(3):
        try:
            await edge_tts.Communicate(text, voice, rate=rate, proxy=proxy).save(path)
            return True
        except Exception as e:  # network hiccups — retry, then give up on this word
            if os.path.exists(path):
                os.remove(path)
            if attempt == 2:
                print(f"  ! {text}: {e}")
            await asyncio.sleep(1 + attempt * 2)
    return False


async def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--voice", default="en-US-AriaNeural")
    ap.add_argument("--concurrency", type=int, default=6)
    args = ap.parse_args()

    import edge_tts
    from edge_tts import communicate

    # Corporate / sandbox proxies re-sign TLS; trust their CA if one is configured.
    ca = os.environ.get("SSL_CERT_FILE")
    if ca and os.path.exists(ca):
        communicate._SSL_CTX.load_verify_locations(ca)
    proxy = os.environ.get("HTTPS_PROXY") or os.environ.get("https_proxy")

    words = json.load(open(os.path.join(ROOT, "data", "words.json"), encoding="utf-8"))
    jobs = []
    for w in words:
        s = slug(w["en"])
        if not s:
            continue
        for sub, rate in (("", "+0%"), ("slow", "-30%")):
            path = os.path.join(ROOT, "audio", sub, s + ".mp3")
            if not os.path.exists(path) or os.path.getsize(path) == 0:
                jobs.append((speak_text(w["en"]), path, rate))
    os.makedirs(os.path.join(ROOT, "audio", "slow"), exist_ok=True)
    print(f"{len(words)} words, {len(jobs)} files to generate with {args.voice}")

    sem = asyncio.Semaphore(args.concurrency)
    done = 0

    async def run(job):
        nonlocal done
        async with sem:
            await voice_one(edge_tts, job[0], job[1], args.voice, job[2], proxy)
            done += 1
            if done % 50 == 0 or done == len(jobs):
                print(f"  {done}/{len(jobs)}")

    await asyncio.gather(*(run(j) for j in jobs))
    write_index()


def write_index():
    have = sorted(f[:-4] for f in os.listdir(os.path.join(ROOT, "audio")) if f.endswith(".mp3"))
    with open(os.path.join(ROOT, "js", "audio.js"), "w", encoding="utf-8") as f:
        f.write("// Generated by scripts/make_audio.py — words that have an mp3 in audio/.\n")
        f.write("window.AUDIO = " + json.dumps(have) + ";\n")
    print(f"js/audio.js: {len(have)} words with audio")


if __name__ == "__main__":
    asyncio.run(main())
